CREATE TYPE EMAIL_STATUS AS ENUM('SENT', 'ERROR');
CREATE CAST (character varying AS EMAIL_STATUS) WITH INOUT AS ASSIGNMENT;

CREATE TABLE emails (
    id UUID NOT NULL PRIMARY KEY,
    owner_ref VARCHAR(100) NOT NULL,
    email_from VARCHAR(100) NOT NULL,
    email_to VARCHAR(100) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    body TEXT NOT NULL,
    status EMAIL_STATUS NOT NULL,
    send_date DATE NOT NULL
);